---
title: "Tutorial 1"
subtitle: "Reproducible programming with [`Quarto`](https://quarto.org)"
editor: source
---

We are going to use the `Quarto` publishing environment to create a reproducible research compendium. This is the first of two `Quarto`-related tutorials. In this tutorial, we will set up the project structure and fill the dummy scripts with some code. In [the second tutorial](tutorial_2.html), we will publish the compendium and create a reproducible manuscript.

# Tutorial materials
The tutorial materials consist of a project structure and dummy scripts that we will use, fill and publish (in [the second tutorial](_site/tutorial_2.html)). 

1. Right-click on the following link and select _Save Link As..._: [my-reproducible-manuscript.zip](https://github.com/UtrechtUniversity/workshop-reproducible-manuscripts/raw/main/my-reproducible-manuscript.zip)
2. Save the zip file in a location that you can easily access. We recommend to **not** use the default download location of your browser.
3. Extract the contents of the zipped file.

The materials should look like this:

```
my-reproducible-manuscript
├── data
│   └── data.csv
├── docs
├── results
└── scripts
│   ├── do_addition.py
│   ├── do_addition.R
│   ├── dummy.py
│   └── dummy.R
├── LICENSE.md
└── README.md
```